/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GoalContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "participate"
      | "goalAmount"
      | "goalOwner"
      | "goalToken"
      | "participants"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "participate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "goalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "goalOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "goalToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participants",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "participate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goalAmount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "goalOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "goalToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participants",
    data: BytesLike
  ): Result;
}

export interface GoalContract extends BaseContract {
  connect(runner?: ContractRunner | null): GoalContract;
  waitForDeployment(): Promise<this>;

  interface: GoalContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  participate: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  goalAmount: TypedContractMethod<[], [bigint], "view">;

  goalOwner: TypedContractMethod<[], [string], "view">;

  goalToken: TypedContractMethod<[], [string], "view">;

  participants: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { amount: bigint; participated: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "participate"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "goalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goalOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "goalToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participants"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { amount: bigint; participated: boolean }],
    "view"
  >;

  filters: {};
}
