/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GoalContract } from "./GoalContract";
export * as factories from "./factories";
export { GoalContract__factory } from "./factories/GoalContract__factory";
